// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/metrics/tunstats (interfaces: VPNLooper,LinkLister,Logger)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=tunstats . VPNLooper,LinkLister,Logger
//

// Package tunstats is a generated GoMock package.
package tunstats

import (
	reflect "reflect"

	settings "github.com/qdm12/gluetun/internal/configuration/settings"
	netlink "github.com/qdm12/gluetun/internal/netlink"
	gomock "go.uber.org/mock/gomock"
)

// MockVPNLooper is a mock of VPNLooper interface.
type MockVPNLooper struct {
	ctrl     *gomock.Controller
	recorder *MockVPNLooperMockRecorder
	isgomock struct{}
}

// MockVPNLooperMockRecorder is the mock recorder for MockVPNLooper.
type MockVPNLooperMockRecorder struct {
	mock *MockVPNLooper
}

// NewMockVPNLooper creates a new mock instance.
func NewMockVPNLooper(ctrl *gomock.Controller) *MockVPNLooper {
	mock := &MockVPNLooper{ctrl: ctrl}
	mock.recorder = &MockVPNLooperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVPNLooper) EXPECT() *MockVPNLooperMockRecorder {
	return m.recorder
}

// GetSettings mocks base method.
func (m *MockVPNLooper) GetSettings() settings.VPN {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettings")
	ret0, _ := ret[0].(settings.VPN)
	return ret0
}

// GetSettings indicates an expected call of GetSettings.
func (mr *MockVPNLooperMockRecorder) GetSettings() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettings", reflect.TypeOf((*MockVPNLooper)(nil).GetSettings))
}

// MockLinkLister is a mock of LinkLister interface.
type MockLinkLister struct {
	ctrl     *gomock.Controller
	recorder *MockLinkListerMockRecorder
	isgomock struct{}
}

// MockLinkListerMockRecorder is the mock recorder for MockLinkLister.
type MockLinkListerMockRecorder struct {
	mock *MockLinkLister
}

// NewMockLinkLister creates a new mock instance.
func NewMockLinkLister(ctrl *gomock.Controller) *MockLinkLister {
	mock := &MockLinkLister{ctrl: ctrl}
	mock.recorder = &MockLinkListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLinkLister) EXPECT() *MockLinkListerMockRecorder {
	return m.recorder
}

// LinkByName mocks base method.
func (m *MockLinkLister) LinkByName(name string) (netlink.Link, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkByName", name)
	ret0, _ := ret[0].(netlink.Link)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LinkByName indicates an expected call of LinkByName.
func (mr *MockLinkListerMockRecorder) LinkByName(name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkByName", reflect.TypeOf((*MockLinkLister)(nil).LinkByName), name)
}

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Warn mocks base method.
func (m *MockLogger) Warn(message string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", message)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(message any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), message)
}
