// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/healthcheck (interfaces: dnsChecker)
//
// Generated by this command:
//
//	mockgen -destination=dns_checker_mock_test.go -package healthcheck . dnsChecker
//

// Package healthcheck is a generated GoMock package.
package healthcheck

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockdnsChecker is a mock of dnsChecker interface.
type MockdnsChecker struct {
	ctrl     *gomock.Controller
	recorder *MockdnsCheckerMockRecorder
	isgomock struct{}
}

// MockdnsCheckerMockRecorder is the mock recorder for MockdnsChecker.
type MockdnsCheckerMockRecorder struct {
	mock *MockdnsChecker
}

// NewMockdnsChecker creates a new mock instance.
func NewMockdnsChecker(ctrl *gomock.Controller) *MockdnsChecker {
	mock := &MockdnsChecker{ctrl: ctrl}
	mock.recorder = &MockdnsCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdnsChecker) EXPECT() *MockdnsCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockdnsChecker) Check(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockdnsCheckerMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockdnsChecker)(nil).Check), ctx)
}
