// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/healthcheck (interfaces: icmpEchoer)
//
// Generated by this command:
//
//	mockgen -destination=icmp_echoer_mock_test.go -package healthcheck . icmpEchoer
//

// Package healthcheck is a generated GoMock package.
package healthcheck

import (
	context "context"
	netip "net/netip"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockicmpEchoer is a mock of icmpEchoer interface.
type MockicmpEchoer struct {
	ctrl     *gomock.Controller
	recorder *MockicmpEchoerMockRecorder
	isgomock struct{}
}

// MockicmpEchoerMockRecorder is the mock recorder for MockicmpEchoer.
type MockicmpEchoerMockRecorder struct {
	mock *MockicmpEchoer
}

// NewMockicmpEchoer creates a new mock instance.
func NewMockicmpEchoer(ctrl *gomock.Controller) *MockicmpEchoer {
	mock := &MockicmpEchoer{ctrl: ctrl}
	mock.recorder = &MockicmpEchoerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockicmpEchoer) EXPECT() *MockicmpEchoerMockRecorder {
	return m.recorder
}

// Echo mocks base method.
func (m *MockicmpEchoer) Echo(ctx context.Context, ip netip.Addr) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Echo", ctx, ip)
	ret0, _ := ret[0].(error)
	return ret0
}

// Echo indicates an expected call of Echo.
func (mr *MockicmpEchoerMockRecorder) Echo(ctx, ip any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Echo", reflect.TypeOf((*MockicmpEchoer)(nil).Echo), ctx, ip)
}

// Reset mocks base method.
func (m *MockicmpEchoer) Reset() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Reset")
}

// Reset indicates an expected call of Reset.
func (mr *MockicmpEchoerMockRecorder) Reset() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reset", reflect.TypeOf((*MockicmpEchoer)(nil).Reset))
}
