// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces_local.go
//
// Generated by this command:
//
//	mockgen -destination=mocks_local_test.go -package=nftables -source=interfaces_local.go -mock_names=conn=MockConn
//

// Package nftables is a generated GoMock package.
package nftables

import (
	reflect "reflect"

	nftables "github.com/google/nftables"
	gomock "go.uber.org/mock/gomock"
)

// MockConn is a mock of conn interface.
type MockConn struct {
	ctrl     *gomock.Controller
	recorder *MockConnMockRecorder
	isgomock struct{}
}

// MockConnMockRecorder is the mock recorder for MockConn.
type MockConnMockRecorder struct {
	mock *MockConn
}

// NewMockConn creates a new mock instance.
func NewMockConn(ctrl *gomock.Controller) *MockConn {
	mock := &MockConn{ctrl: ctrl}
	mock.recorder = &MockConnMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConn) EXPECT() *MockConnMockRecorder {
	return m.recorder
}

// AddChain mocks base method.
func (m *MockConn) AddChain(chain *nftables.Chain) *nftables.Chain {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddChain", chain)
	ret0, _ := ret[0].(*nftables.Chain)
	return ret0
}

// AddChain indicates an expected call of AddChain.
func (mr *MockConnMockRecorder) AddChain(chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddChain", reflect.TypeOf((*MockConn)(nil).AddChain), chain)
}

// AddRule mocks base method.
func (m *MockConn) AddRule(rule *nftables.Rule) *nftables.Rule {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRule", rule)
	ret0, _ := ret[0].(*nftables.Rule)
	return ret0
}

// AddRule indicates an expected call of AddRule.
func (mr *MockConnMockRecorder) AddRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRule", reflect.TypeOf((*MockConn)(nil).AddRule), rule)
}

// AddTable mocks base method.
func (m *MockConn) AddTable(table *nftables.Table) *nftables.Table {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddTable", table)
	ret0, _ := ret[0].(*nftables.Table)
	return ret0
}

// AddTable indicates an expected call of AddTable.
func (mr *MockConnMockRecorder) AddTable(table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddTable", reflect.TypeOf((*MockConn)(nil).AddTable), table)
}

// DelRule mocks base method.
func (m *MockConn) DelRule(rule *nftables.Rule) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelRule", rule)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelRule indicates an expected call of DelRule.
func (mr *MockConnMockRecorder) DelRule(rule any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelRule", reflect.TypeOf((*MockConn)(nil).DelRule), rule)
}

// DelTable mocks base method.
func (m *MockConn) DelTable(table *nftables.Table) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DelTable", table)
}

// DelTable indicates an expected call of DelTable.
func (mr *MockConnMockRecorder) DelTable(table any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelTable", reflect.TypeOf((*MockConn)(nil).DelTable), table)
}

// Flush mocks base method.
func (m *MockConn) Flush() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush")
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockConnMockRecorder) Flush() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockConn)(nil).Flush))
}

// FlushChain mocks base method.
func (m *MockConn) FlushChain(chain *nftables.Chain) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "FlushChain", chain)
}

// FlushChain indicates an expected call of FlushChain.
func (mr *MockConnMockRecorder) FlushChain(chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FlushChain", reflect.TypeOf((*MockConn)(nil).FlushChain), chain)
}

// GetRules mocks base method.
func (m *MockConn) GetRules(table *nftables.Table, chain *nftables.Chain) ([]*nftables.Rule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRules", table, chain)
	ret0, _ := ret[0].([]*nftables.Rule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRules indicates an expected call of GetRules.
func (mr *MockConnMockRecorder) GetRules(table, chain any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRules", reflect.TypeOf((*MockConn)(nil).GetRules), table, chain)
}

// ListChains mocks base method.
func (m *MockConn) ListChains() ([]*nftables.Chain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListChains")
	ret0, _ := ret[0].([]*nftables.Chain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListChains indicates an expected call of ListChains.
func (mr *MockConnMockRecorder) ListChains() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListChains", reflect.TypeOf((*MockConn)(nil).ListChains))
}

// ListTables mocks base method.
func (m *MockConn) ListTables() ([]*nftables.Table, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTables")
	ret0, _ := ret[0].([]*nftables.Table)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTables indicates an expected call of ListTables.
func (mr *MockConnMockRecorder) ListTables() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTables", reflect.TypeOf((*MockConn)(nil).ListTables))
}
