name: Bug
description: Report a bug
title: "Bug: "
labels: [":bug: bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        ⚠️ PLEASE set a **title** for the issue ☝️
  - type: dropdown
    id: latest
    attributes:
      label: Is this bug present on the latest image (`:master` branch)?
      description: |
        Don't forget to re-pull the latest image to make sure you are running the last pushed `:latest` image tag.
        Note this is NOT the same as the latest stable release (i.e. `:v3.41.3`).
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  - type: dropdown
    id: last-stable
    attributes:
      label: Is this bug present on the last stable image?
      description: |
        Make sure you use the latest `:v3.x.y` release tag from [here](https://github.com/passteque/gluetun/releases)
        Answering this allows to find if this is a regression bug or not.
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  - type: input
    id: host-os
    attributes:
      label: Host OS
      description: What is your host OS?
      placeholder: "Debian Buster"
  - type: dropdown
    id: cpu-arch
    attributes:
      label: CPU arch
      description: You can find it on Linux with `uname -m`.
      options:
        - x86_64
        - aarch64
        - armv7l
        - "386"
        - s390x
        - ppc64le
  - type: dropdown
    id: vpn-service-provider
    attributes:
      label: VPN service provider
      options:
        - AirVPN
        - Custom
        - Cyberghost
        - ExpressVPN
        - FastestVPN
        - Giganews
        - HideMyAss
        - IPVanish
        - IVPN
        - Mullvad
        - NordVPN
        - Privado
        - Private Internet Access
        - PrivateVPN
        - ProtonVPN
        - PureVPN
        - SlickVPN
        - Surfshark
        - TorGuard
        - VPNSecure.me
        - VPNUnlimited
        - VyprVPN
        - Windscribe
    validations:
      required: true
  - type: dropdown
    id: docker
    attributes:
      label: What are you using to run the container
      options:
        - docker run
        - docker-compose
        - Portainer
        - Kubernetes
        - Podman
        - Unraid
        - Other
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: "What's the problem 🤔"
      placeholder: "That feature does not work..."
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Share your logs (at least 10 lines). Share the version string logged at the beginning PLEASE!!
      description: No sensitive information is logged out except when running with `LOG_LEVEL=debug`.
      render: plain text
    validations:
      required: true
  - type: textarea
    id: config
    attributes:
      label: Share your configuration
      description: Share your configuration such as `docker-compose.yml`. Ensure to remove credentials.
      render: yml
