// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/portforward/service (interfaces: Logger,PortAllower)
//
// Generated by this command:
//
//	mockgen -destination=internal/portforward/service/mocks_test.go -package=service github.com/qdm12/gluetun/internal/portforward/service Logger,PortAllower
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockLogger is a mock of Logger interface.
type MockLogger struct {
	ctrl     *gomock.Controller
	recorder *MockLoggerMockRecorder
	isgomock struct{}
}

// MockLoggerMockRecorder is the mock recorder for MockLogger.
type MockLoggerMockRecorder struct {
	mock *MockLogger
}

// NewMockLogger creates a new mock instance.
func NewMockLogger(ctrl *gomock.Controller) *MockLogger {
	mock := &MockLogger{ctrl: ctrl}
	mock.recorder = &MockLoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLogger) EXPECT() *MockLoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockLogger) Debug(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", s)
}

// Debug indicates an expected call of Debug.
func (mr *MockLoggerMockRecorder) Debug(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockLogger)(nil).Debug), s)
}

// Error mocks base method.
func (m *MockLogger) Error(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", s)
}

// Error indicates an expected call of Error.
func (mr *MockLoggerMockRecorder) Error(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockLogger)(nil).Error), s)
}

// Info mocks base method.
func (m *MockLogger) Info(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", s)
}

// Info indicates an expected call of Info.
func (mr *MockLoggerMockRecorder) Info(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockLogger)(nil).Info), s)
}

// Warn mocks base method.
func (m *MockLogger) Warn(s string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warn", s)
}

// Warn indicates an expected call of Warn.
func (mr *MockLoggerMockRecorder) Warn(s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warn", reflect.TypeOf((*MockLogger)(nil).Warn), s)
}

// MockPortAllower is a mock of PortAllower interface.
type MockPortAllower struct {
	ctrl     *gomock.Controller
	recorder *MockPortAllowerMockRecorder
	isgomock struct{}
}

// MockPortAllowerMockRecorder is the mock recorder for MockPortAllower.
type MockPortAllowerMockRecorder struct {
	mock *MockPortAllower
}

// NewMockPortAllower creates a new mock instance.
func NewMockPortAllower(ctrl *gomock.Controller) *MockPortAllower {
	mock := &MockPortAllower{ctrl: ctrl}
	mock.recorder = &MockPortAllowerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPortAllower) EXPECT() *MockPortAllowerMockRecorder {
	return m.recorder
}

// RedirectPort mocks base method.
func (m *MockPortAllower) RedirectPort(ctx context.Context, intf string, sourcePort, destinationPort uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RedirectPort", ctx, intf, sourcePort, destinationPort)
	ret0, _ := ret[0].(error)
	return ret0
}

// RedirectPort indicates an expected call of RedirectPort.
func (mr *MockPortAllowerMockRecorder) RedirectPort(ctx, intf, sourcePort, destinationPort any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RedirectPort", reflect.TypeOf((*MockPortAllower)(nil).RedirectPort), ctx, intf, sourcePort, destinationPort)
}

// RemoveAllowedPort mocks base method.
func (m *MockPortAllower) RemoveAllowedPort(ctx context.Context, port uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllowedPort", ctx, port)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllowedPort indicates an expected call of RemoveAllowedPort.
func (mr *MockPortAllowerMockRecorder) RemoveAllowedPort(ctx, port any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllowedPort", reflect.TypeOf((*MockPortAllower)(nil).RemoveAllowedPort), ctx, port)
}

// SetAllowedPort mocks base method.
func (m *MockPortAllower) SetAllowedPort(ctx context.Context, port uint16, intf string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAllowedPort", ctx, port, intf)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAllowedPort indicates an expected call of SetAllowedPort.
func (mr *MockPortAllowerMockRecorder) SetAllowedPort(ctx, port, intf any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAllowedPort", reflect.TypeOf((*MockPortAllower)(nil).SetAllowedPort), ctx, port, intf)
}
