// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qdm12/gluetun/internal/metrics/prometheus (interfaces: Gatherer)
//
// Generated by this command:
//
//	mockgen -destination=mocks_test.go -package=prometheus . Gatherer
//

// Package prometheus is a generated GoMock package.
package prometheus

import (
	reflect "reflect"

	io_prometheus_client "github.com/prometheus/client_model/go"
	gomock "go.uber.org/mock/gomock"
)

// MockGatherer is a mock of Gatherer interface.
type MockGatherer struct {
	ctrl     *gomock.Controller
	recorder *MockGathererMockRecorder
	isgomock struct{}
}

// MockGathererMockRecorder is the mock recorder for MockGatherer.
type MockGathererMockRecorder struct {
	mock *MockGatherer
}

// NewMockGatherer creates a new mock instance.
func NewMockGatherer(ctrl *gomock.Controller) *MockGatherer {
	mock := &MockGatherer{ctrl: ctrl}
	mock.recorder = &MockGathererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGatherer) EXPECT() *MockGathererMockRecorder {
	return m.recorder
}

// Gather mocks base method.
func (m *MockGatherer) Gather() ([]*io_prometheus_client.MetricFamily, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Gather")
	ret0, _ := ret[0].([]*io_prometheus_client.MetricFamily)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Gather indicates an expected call of Gather.
func (mr *MockGathererMockRecorder) Gather() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Gather", reflect.TypeOf((*MockGatherer)(nil).Gather))
}
